import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import { ArrowRight, BookOpen, Plus, Search, X } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "../components/ui/alert";
import { Button } from "../components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "../components/ui/dialog";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "../components/ui/empty";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "../components/ui/field";
import { Input } from "../components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Separator } from "../components/ui/separator";
import { Textarea } from "../components/ui/textarea";
import { api, projectPath, type CreativeProjectDraft, type ProjectSummary } from "../lib/api";
import { AppShell } from "../components/layout/app-shell";

export function ProjectLibrary({ onChat, initialDraft, onDraftConsumed }: { onChat: () => void; initialDraft?: CreativeProjectDraft | null; onDraftConsumed?: () => void }) {
  const [projects, setProjects] = useState<ProjectSummary[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [creating, setCreating] = useState(false); const [query, setQuery] = useState(""); const [draftRevision, setDraftRevision] = useState(0);
  const openCreate = () => { setDraftRevision((revision) => revision + 1); setCreating(true); };
  const load = () => { setLoading(true); setError(""); void api<{ projects: ProjectSummary[] }>("/api/projects").then((response) => setProjects(response.projects)).catch((cause) => setError(cause instanceof Error ? cause.message : "加载失败")).finally(() => setLoading(false)); };
  useEffect(load, []);
  useEffect(() => { if (initialDraft) { setDraftRevision((revision) => revision + 1); setCreating(true); } }, [initialDraft]);
  const visible = projects.filter((project) => project.novelTitle.toLocaleLowerCase("zh-CN").includes(query.trim().toLocaleLowerCase("zh-CN")) || project.projectId.toLowerCase().includes(query.trim().toLowerCase()));
  return <AppShell onRefresh={load} onNewProject={openCreate} onChat={onChat}>
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2"><Badge variant="outline">PROJECT LIBRARY</Badge><span className="text-xs text-muted-foreground">{projects.length} 个项目</span></div><h1 className="text-3xl font-semibold tracking-tight">小说项目</h1><p className="mt-2 text-sm text-muted-foreground">项目、进度与最近运行状态。</p></div><Button onClick={openCreate}><Plus data-icon="inline-start" />新建项目</Button></header>
    <Card><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>项目列表</CardTitle><CardDescription>选择一个项目进入 Graph 工作区。</CardDescription></div><div className="relative w-full sm:w-72"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="查找项目" value={query} onChange={(event) => setQuery(event.target.value)} /></div></CardHeader><Separator />
      <CardContent className="p-0">{loading ? <div className="p-6 text-sm text-muted-foreground">正在加载项目…</div> : error ? <Alert variant="destructive" className="m-4"><AlertTitle>项目加载失败</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : visible.length === 0 ? <Empty className="min-h-64 border-0"><EmptyHeader><EmptyMedia variant="icon"><BookOpen /></EmptyMedia><EmptyTitle>{projects.length ? "没有匹配的项目" : "还没有项目"}</EmptyTitle><EmptyDescription>{projects.length ? "尝试调整搜索条件。" : "先创建一部小说，Graph 工作区会从 Foundation 开始。"}</EmptyDescription></EmptyHeader><EmptyContent>{projects.length === 0 && <Button onClick={openCreate}><Plus data-icon="inline-start" />创建项目</Button>}</EmptyContent></Empty> : <div className="divide-y">{visible.map((project) => <div key={project.projectId} className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-muted"><BookOpen /></span><div className="min-w-0"><h2 className="truncate font-medium">{project.novelTitle}</h2><code className="text-xs text-muted-foreground">{project.projectId}</code></div></div><div className="flex items-center gap-3"><Badge variant={project.status === "failed" ? "destructive" : project.status === "running" ? "secondary" : "outline"}>{project.status}</Badge><Button variant="outline" size="sm" asChild><a href={projectPath(project.projectId, "overview")}>打开项目<ArrowRight data-icon="inline-end" /></a></Button></div></div>)}</div>}</CardContent></Card>
    <Dialog open={creating} onOpenChange={(open) => { setCreating(open); if (!open) onDraftConsumed?.(); }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>创建一部新小说</DialogTitle><DialogDescription>先写清楚故事，再让 Graph 引擎接手推进。</DialogDescription></DialogHeader><CreateProject key={draftRevision} initialDraft={initialDraft} onCreated={(projectId) => { setCreating(false); onDraftConsumed?.(); window.location.href = projectPath(projectId, "overview"); }} onCancel={() => { setCreating(false); onDraftConsumed?.(); }} /><DialogFooter><Button variant="outline" type="button" onClick={() => { setCreating(false); onDraftConsumed?.(); }}><X data-icon="inline-start" />取消</Button></DialogFooter></DialogContent></Dialog>
  </AppShell>;
}

function CreateProject({ initialDraft, onCreated, onCancel }: { initialDraft?: CreativeProjectDraft | null; onCreated: (projectId: string) => void; onCancel: () => void }) {
  const [form, setForm] = useState(() => ({ novelTitle: initialDraft?.novelTitle ?? "", projectId: "", creativeGenre: initialDraft?.creativeGenre ?? "", creativePremise: initialDraft?.creativePremise ?? "", creativeTheme: initialDraft?.creativeTheme ?? "", creativeNotes: initialDraft?.creativeNotes ?? "", targetTotalChapters: String(initialDraft?.targetTotalChapters ?? 12), targetTotalWords: String(initialDraft?.targetTotalWords ?? 0) })); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const update = (key: keyof typeof form) => (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm((value) => ({ ...value, [key]: event.target.value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await api<{ project: { projectId: string } }>("/api/projects", { method: "POST", body: JSON.stringify({ ...form, targetTotalChapters: Number(form.targetTotalChapters), targetTotalWords: Number(form.targetTotalWords), projectId: form.projectId || undefined }) }); onCreated(response.project.projectId); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建失败"); setBusy(false); } }
  return <form className="flex flex-col gap-4" onSubmit={submit}><FieldGroup><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="novel-title">小说标题 *</FieldLabel><Input id="novel-title" value={form.novelTitle} onChange={update("novelTitle")} required maxLength={200} /></Field><Field><FieldLabel htmlFor="project-id">项目 ID（可选）</FieldLabel><Input id="project-id" value={form.projectId} onChange={update("projectId")} maxLength={80} /></Field><Field><FieldLabel htmlFor="genre">题材</FieldLabel><Input id="genre" value={form.creativeGenre} onChange={update("creativeGenre")} maxLength={200} /></Field><Field><FieldLabel htmlFor="chapters">目标章节</FieldLabel><Input id="chapters" type="number" min="1" value={form.targetTotalChapters} onChange={update("targetTotalChapters")} required /></Field><Field><FieldLabel htmlFor="words">目标字数</FieldLabel><Input id="words" type="number" min="0" max="20000000" value={form.targetTotalWords} onChange={update("targetTotalWords")} required /></Field><Field><FieldLabel htmlFor="theme">主题</FieldLabel><Input id="theme" value={form.creativeTheme} onChange={update("creativeTheme")} maxLength={200} /></Field></div><Field><FieldLabel htmlFor="premise">故事前提</FieldLabel><Textarea id="premise" className="min-h-24" value={form.creativePremise} onChange={update("creativePremise")} maxLength={2000} /><FieldDescription>描述主角、核心冲突和你希望读者持续获得的体验。</FieldDescription></Field><Field><FieldLabel htmlFor="notes">创作备注</FieldLabel><Textarea id="notes" className="min-h-24" value={form.creativeNotes} onChange={update("creativeNotes")} maxLength={4000} /></Field></FieldGroup>{error && <Alert variant="destructive"><AlertTitle>创建失败</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<div className="flex justify-end"><Button type="submit" disabled={busy || !form.novelTitle.trim()}>{busy ? "创建中…" : "创建并打开"}<ArrowRight data-icon="inline-end" /></Button></div></form>;
}
