import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ChevronLeft, ChevronRight, Library, Search } from "lucide-react";
import { AppShell } from "./components/layout/app-shell";
import { Alert, AlertDescription } from "./components/ui/alert";
import { Badge } from "./components/ui/badge";
import { Button } from "./components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "./components/ui/empty";
import { Input } from "./components/ui/input";
import { Label } from "./components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./components/ui/select";
import { Separator } from "./components/ui/separator";
import { ScrollArea } from "./components/ui/scroll-area";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "./components/ui/sheet";
import { Skeleton } from "./components/ui/skeleton";

type Chapter = { chapterNumber: number; title: string; summary: string; content: string };
type Novel = { projectId: string; novelTitle: string; chapters: Chapter[] };
const recentKey = "graphnovel.reader.recent";
const chapterKey = (id: string) => `graphnovel.reader.chapter.${id}`;

async function getNovels(): Promise<Novel[]> { const response = await fetch("/api/trial-reading"); if (!response.ok) throw new Error("试读内容加载失败"); return (await response.json() as { novels?: Novel[] }).novels ?? []; }
function readRecent(): string[] { try { return JSON.parse(localStorage.getItem(recentKey) ?? "[]") as string[]; } catch { return []; } }
function rememberNovel(id: string) { localStorage.setItem(recentKey, JSON.stringify([id, ...readRecent().filter((item) => item !== id)].slice(0, 5))); }
function readChapter(id: string): number | null { const value = Number(localStorage.getItem(chapterKey(id))); return Number.isInteger(value) && value > 0 ? value : null; }
function updateReaderUrl(novelId: string, chapterNumber: number, replace = false) { const url = `/reader?novel=${encodeURIComponent(novelId)}&chapter=${chapterNumber}`; window.history[replace ? "replaceState" : "pushState"]({}, "", url); }
function locationSelection() { const params = new URLSearchParams(window.location.search); const chapter = Number(params.get("chapter")); return { novelId: params.get("novel"), chapter: Number.isInteger(chapter) && chapter > 0 ? chapter : null }; }

function ChapterDirectory({ novel, current, filter, onSelect }: { novel: Novel; current: number; filter: string; onSelect: (chapter: Chapter) => void }) {
  const normalized = filter.trim().toLocaleLowerCase("zh-CN");
  const chapters = novel.chapters.filter((chapter) => !normalized || String(chapter.chapterNumber).includes(normalized) || chapter.title.toLocaleLowerCase("zh-CN").includes(normalized));
  const groups = useMemo(() => { const map = new Map<string, Chapter[]>(); chapters.forEach((chapter) => { const start = Math.floor((chapter.chapterNumber - 1) / 20) * 20 + 1; const key = `${start}-${start + 19}`; map.set(key, [...(map.get(key) ?? []), chapter]); }); return [...map.entries()]; }, [chapters]);
  if (!chapters.length) return <p className="px-2 py-5 text-sm text-muted-foreground">没有匹配的章节</p>;
  return <div className="grid gap-1">{groups.map(([range, items]) => { const [start, end] = range.split("-").map(Number); return <details key={range} open={!normalized || (current >= start && current <= end)} className="border-t border-border first:border-0"><summary className="cursor-pointer list-none px-2 py-2 text-xs text-muted-foreground hover:text-foreground">第 {range} 章 <span className="float-right">{items.length}</span></summary><div className="grid gap-1 pb-2">{items.map((chapter) => <Button key={chapter.chapterNumber} type="button" title={chapter.title} variant={chapter.chapterNumber === current ? "secondary" : "ghost"} size="sm" onClick={() => onSelect(chapter)} className="h-auto min-w-0 justify-start truncate px-2 py-1.5 text-left text-xs font-normal"><span className="truncate">第{chapter.chapterNumber}章 <span className="opacity-70">· {chapter.title}</span></span></Button>)}</div></details>; })}</div>;
}

export function ReaderPage() {
  const [novels, setNovels] = useState<Novel[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [chapterNumber, setChapterNumber] = useState<number | null>(null); const [novelFilter, setNovelFilter] = useState(""); const [chapterFilter, setChapterFilter] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [mobileDirectory, setMobileDirectory] = useState(false);
  const selectedNovel = novels.find((novel) => novel.projectId === selectedId) ?? novels[0]; const selectedChapter = selectedNovel?.chapters.find((chapter) => chapter.chapterNumber === chapterNumber) ?? selectedNovel?.chapters[0]; const filteredNovels = novels.filter((novel) => novel.novelTitle.toLocaleLowerCase("zh-CN").includes(novelFilter.trim().toLocaleLowerCase("zh-CN"))); const selectableNovels = selectedNovel && !filteredNovels.some((novel) => novel.projectId === selectedNovel.projectId) ? [selectedNovel, ...filteredNovels] : filteredNovels;
  const selectChapter = (novel: Novel, chapter: Chapter, replace = false) => { setSelectedId(novel.projectId); setChapterNumber(chapter.chapterNumber); setChapterFilter(""); setMobileDirectory(false); rememberNovel(novel.projectId); localStorage.setItem(chapterKey(novel.projectId), String(chapter.chapterNumber)); updateReaderUrl(novel.projectId, chapter.chapterNumber, replace); };
  useEffect(() => { getNovels().then((items) => { setNovels(items); const selection = locationSelection(); const novel = items.find((item) => item.projectId === selection.novelId) ?? items.find((item) => readRecent().includes(item.projectId)) ?? items[0]; if (novel) { const chapter = novel.chapters.find((item) => item.chapterNumber === selection.chapter) ?? novel.chapters.find((item) => item.chapterNumber === readChapter(novel.projectId)) ?? novel.chapters[0]; setSelectedId(novel.projectId); setChapterNumber(chapter.chapterNumber); rememberNovel(novel.projectId); updateReaderUrl(novel.projectId, chapter.chapterNumber, true); } }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "加载失败")).finally(() => setLoading(false)); }, []);
  useEffect(() => { const onPop = () => { const selection = locationSelection(); const novel = novels.find((item) => item.projectId === selection.novelId); const chapter = novel?.chapters.find((item) => item.chapterNumber === selection.chapter); if (novel && chapter) { setSelectedId(novel.projectId); setChapterNumber(chapter.chapterNumber); } }; window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, [novels]);
  const reload = () => { setLoading(true); setError(""); void getNovels().then(setNovels).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "加载失败")).finally(() => setLoading(false)); };
  if (loading) return <AppShell route="reader" onRefresh={reload}><ReaderHeader count={null} /><Card><CardContent className="grid min-h-64 place-items-center gap-4"><Skeleton className="h-6 w-56" /><Skeleton className="h-4 w-80" /></CardContent></Card></AppShell>;
  if (error) return <AppShell route="reader" onRefresh={reload}><ReaderHeader count={null} /><Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert></AppShell>;
  if (!novels.length || !selectedNovel || !selectedChapter) return <AppShell route="reader" onRefresh={reload}><ReaderHeader count={0} /><Card><CardContent><Empty><EmptyHeader><EmptyTitle>还没有已批准的正文</EmptyTitle><EmptyDescription>完成并批准章节后，正文会出现在这里。</EmptyDescription></EmptyHeader></Empty></CardContent></Card></AppShell>;
  const index = selectedNovel.chapters.findIndex((chapter) => chapter.chapterNumber === selectedChapter.chapterNumber); const recent = readRecent().map((id) => novels.find((novel) => novel.projectId === id)).filter((novel): novel is Novel => Boolean(novel));
  return <AppShell route="reader" onRefresh={reload}><ReaderHeader count={novels.length} /><Card className="mb-4"><CardHeader><CardTitle className="text-base">选择作品</CardTitle><CardDescription>继续上次阅读，或从其他已完成作品开始。</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-[1fr_20rem]"><div className="grid gap-2"><Label htmlFor="reader-novel-select">当前作品</Label><Select value={selectedNovel.projectId} onValueChange={(value) => { const novel = novels.find((item) => item.projectId === value)!; selectChapter(novel, novel.chapters.find((chapter) => chapter.chapterNumber === readChapter(novel.projectId)) ?? novel.chapters[0]); }}><SelectTrigger id="reader-novel-select"><SelectValue placeholder="选择作品" /></SelectTrigger><SelectContent>{selectableNovels.map((novel) => <SelectItem key={novel.projectId} value={novel.projectId}>{novel.novelTitle} · {novel.chapters.length} 章</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label htmlFor="reader-novel-search">查找作品</Label><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input id="reader-novel-search" value={novelFilter} onChange={(event) => setNovelFilter(event.target.value)} placeholder="输入小说名称" className="pl-9" /></div></div></CardContent>{recent.length > 0 && <><Separator /><CardFooter className="flex-wrap gap-2 pt-4 text-xs text-muted-foreground"><span>最近阅读</span>{recent.map((novel) => <Button key={novel.projectId} variant="ghost" size="sm" onClick={() => selectChapter(novel, novel.chapters.find((chapter) => chapter.chapterNumber === readChapter(novel.projectId)) ?? novel.chapters[0])}>{novel.novelTitle}</Button>)}</CardFooter></>}</Card>
    <div className="grid gap-4 lg:grid-cols-[18rem_minmax(0,1fr)]"><Card className="hidden h-fit lg:block"><CardHeader className="p-4"><CardTitle className="text-sm">章节目录</CardTitle><CardDescription>{selectedNovel.chapters.length} 章</CardDescription></CardHeader><ScrollArea className="max-h-[calc(100vh-13rem)]"><CardContent className="p-2"><ChapterDirectory novel={selectedNovel} current={selectedChapter.chapterNumber} filter={chapterFilter} onSelect={(chapter) => selectChapter(selectedNovel, chapter)} /></CardContent></ScrollArea></Card><Sheet open={mobileDirectory} onOpenChange={setMobileDirectory}><SheetContent side="left"><SheetHeader><SheetTitle>章节目录</SheetTitle><SheetDescription>{selectedNovel.chapters.length} 章 · {selectedNovel.novelTitle}</SheetDescription></SheetHeader><ScrollArea className="h-full px-4"><ChapterDirectory novel={selectedNovel} current={selectedChapter.chapterNumber} filter={chapterFilter} onSelect={(chapter) => selectChapter(selectedNovel, chapter)} /></ScrollArea></SheetContent></Sheet><main className="min-w-0"><div className="mb-3 flex flex-wrap items-end gap-3"><div className="grid min-w-52 flex-1 gap-2"><Label htmlFor="reader-chapter-search">筛选章节</Label><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input id="reader-chapter-search" value={chapterFilter} onChange={(event) => setChapterFilter(event.target.value)} placeholder="章节号或标题关键词" className="pl-9" /></div></div><Button variant="outline" size="sm" className="lg:hidden" onClick={() => setMobileDirectory(true)}><Library />章节目录</Button></div><Card><CardHeader><p className="text-xs text-muted-foreground">第 {selectedChapter.chapterNumber} 章</p><CardTitle className="text-2xl leading-tight">{selectedChapter.title}</CardTitle>{selectedChapter.summary && <CardDescription className="leading-7">{selectedChapter.summary}</CardDescription>}</CardHeader><CardContent><div className="reader-prose">{selectedChapter.content}</div></CardContent><CardFooter className="justify-between gap-3"><Button variant="outline" disabled={index <= 0} onClick={() => selectChapter(selectedNovel, selectedNovel.chapters[index - 1])}><ChevronLeft />上一章</Button><Button variant="outline" disabled={index >= selectedNovel.chapters.length - 1} onClick={() => selectChapter(selectedNovel, selectedNovel.chapters[index + 1])}>下一章<ChevronRight /></Button></CardFooter></Card></main></div>
  </AppShell>;
}

function ReaderHeader({ count }: { count: number | null }) { return <header className="mb-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-medium tracking-widest text-muted-foreground">READER</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">试读中心</h1><p className="mt-1 text-sm text-muted-foreground">只展示已批准的完整正文{count === null ? "" : ` · ${count} 部作品`}。</p></div><Badge variant="outline">只读</Badge></div></header>; }
